application: goikens
version: 1-1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bootstrap
  static_dir: bootstrap

- url: /static_files
  static_dir: static_files

- url: /.*
  script: index.app

libraries:
- name: jinja2
  version: latest

